DROP TABLE IF EXISTS orderProd;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS department;
